export default {
  ON_LOAD: "ON_LOAD",
  CREATE_ACTIVITY: "CREATE_ACTIVITY",
  DRAFT_ACTIVITY: "DRAFT_ACTIVITY",
  EDIT_ACTIVITY: "EDIT_ACTIVITY",
  CANCEL_ACTIVITY: "CANCEL_ACTIVITY",
  RECIEVE_ACTIVITIES: "RECIEVE_ACTIVITIES"
};
